CREATE USER 'user_check'@'%' 
IDENTIFIED BY 'userPass';
GRANT SELECT ON *.* TO 'user_check'@'%' 
REQUIRE NONE
WITH 
MAX_QUERIES_PER_HOUR 0 
MAX_CONNECTIONS_PER_HOUR 0 
MAX_UPDATES_PER_HOUR 0 
MAX_USER_CONNECTIONS 0;
GRANT ALL PRIVILEGES ON `file_storage`.* TO 'user_check'@'%'; 

CREATE USER 'user_insert'@'%' 
IDENTIFIED BY 'userPass';
GRANT INSERT ON *.* TO 'user_insert'@'%' 
REQUIRE NONE
WITH 
MAX_QUERIES_PER_HOUR 0 
MAX_CONNECTIONS_PER_HOUR 0 
MAX_UPDATES_PER_HOUR 0 
MAX_USER_CONNECTIONS 0;
GRANT ALL PRIVILEGES ON `file_storage`.* TO 'user_insert'@'%'; 

CREATE USER 'user_select'@'%' 
IDENTIFIED BY 'userPass';
GRANT SELECT ON *.* TO 'user_select'@'%' 
REQUIRE NONE
WITH 
MAX_QUERIES_PER_HOUR 0 
MAX_CONNECTIONS_PER_HOUR 0 
MAX_UPDATES_PER_HOUR 0 
MAX_USER_CONNECTIONS 0;
GRANT ALL PRIVILEGES ON `file_storage`.* TO 'user_select'@'%';

CREATE USER 'user_delete'@'%' 
IDENTIFIED BY 'userPass';
GRANT DELETE ON *.* TO 'user_delete'@'%' 
REQUIRE NONE
WITH 
MAX_QUERIES_PER_HOUR 0 
MAX_CONNECTIONS_PER_HOUR 0 
MAX_UPDATES_PER_HOUR 0 
MAX_USER_CONNECTIONS 0;
GRANT ALL PRIVILEGES ON `file_storage`.* TO 'user_delete'@'%'; 